In [3]:
import numpy as np

In [2]:
1D List -> Numpy array
2D Matrix -> Numpy array

SyntaxError: invalid syntax (<ipython-input-2-0f081e863aae>, line 1)

In [1]:
vec = [1, 2, 3]

In [4]:
np_vec = np.array(vec)

In [5]:
np_vec

array([1, 2, 3])

In [6]:
type(np_vec)

numpy.ndarray

In [7]:
mat = [[2,6,8], [3,7,0]]

In [8]:
np_mat = np.array(mat)

In [9]:
np_mat

array([[2, 6, 8],
       [3, 7, 0]])

In [ ]:
Zeros, Ones, Eye

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.randn(5)

array([-0.05734927, -0.94106474, -0.05542286, -0.16098582,  0.01759669])

In [15]:
np.random.randn(3,4)

array([[ 1.00650478,  0.55802293,  0.24775934, -0.07080545],
       [ 0.96791805, -0.67185516, -1.54243958,  0.01636758],
       [ 0.12313166,  0.89435766,  0.79251148,  1.65555266]])

In [16]:
np.random.randint(5,15)

9

In [18]:
np.random.randint(5,1235,5)

array([432, 688, 163, 791, 631])

In [21]:
np.arange(3,12,3)

array([3, 6, 9])

In [22]:
np_mat.shape

(2, 3)

In [23]:
np_mat.reshape(3,2)

array([[2, 6],
       [8, 3],
       [7, 0]])

In [24]:
np_mat.dtype

dtype('int64')

In [25]:
a = np.array([0,1,2,3,4,5])

In [26]:
a + 7

array([ 7,  8,  9, 10, 11, 12])

In [27]:
a -2

array([-2, -1,  0,  1,  2,  3])

In [28]:
np.sum(a)

15

In [29]:
np.mean(a)

2.5

In [31]:
a1 = np.array([[1,3], [4,6]])
b1 = np.array([[0,2], [3,1]])

In [32]:
a1

array([[1, 3],
       [4, 6]])

In [33]:
a > 2

array([False, False, False,  True,  True,  True])

In [34]:
d1 = np.arange(25)

In [35]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
d2 = np.arange(25).reshape(5,5)

In [38]:
d2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
d1[start: end+1]

NameError: name 'start' is not defined

In [40]:
d1[4:12]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
d1[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24])

In [42]:
d1[:13]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
d2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
d2[0,0]

0

In [45]:
d2[2,2]

12

In [46]:
d2[2,1]

11

In [50]:
d2[:, 3]

array([ 3,  8, 13, 18, 23])

In [51]:
d2[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [52]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
d1[0:5] = -10

In [ ]:
d